### ISSUE TITLE
couldn't find "libDeviceConfig.so"

### ISSUE THREAD

**Issue by X-SLAYER** [AuliaVailo/flutter_pax_printer_utility#11]
i made an app and i run on a Pax E700 device it's Android and already have an app with android native that print and works fine but when I tried to use Flutter and this library I got that error 

```
E/IPP_DAL_TAG(31235): 05-15 20:48:27.712 DAL VERSION:V3.20.00_20201229
I/Test    (31235): Get dal cost:216 ms
E/AndroidRuntime(31235): FATAL EXCEPTION: main
E/AndroidRuntime(31235): Process: app.cash.grip, PID: 31235
E/AndroidRuntime(31235): java.lang.UnsatisfiedLinkError: dalvik.system.DexClassLoader[DexPathList[[dex file "/data/user/0/app.cash.grip/files/nepcore.dex"],nativeLibraryDirectories=[/data/app/app.cash.grip-1/lib/arm64, /system/lib64, /vendor/lib64]]] couldn't find "libDeviceConfig.so"
E/AndroidRuntime(31235): 	at java.lang.Runtime.loadLibrary0(Runtime.java:984)
E/AndroidRuntime(31235): 	at java.lang.System.loadLibrary(System.java:1562)
E/AndroidRuntime(31235): 	at com.pax.dal.impl.utils.DeviceConfig.<clinit>(SourceFile:22)
E/AndroidRuntime(31235): 	at com.pax.dal.impl.utils.ServiceUtils.getDeviceEnable(SourceFile:90)
E/AndroidRuntime(31235): 	at com.pax.dal.impl.utils.ServiceUtils.isModuleEnable(SourceFile:102)
E/AndroidRuntime(31235): 	at com.pax.dal.impl.D.u(SourceFile:121)
E/AndroidRuntime(31235): 	at com.pax.dal.impl.D.init(SourceFile:128)
E/AndroidRuntime(31235): 	at com.pax.dal.impl.PrinterImplDecorator.init(SourceFile:55)
E/AndroidRuntime(31235): 	at com.mahatech.flutter_pax_printer_utility.PrinterUtility.init(PrinterUtility.java:43)
E/AndroidRuntime(31235): 	at com.mahatech.flutter_pax_printer_utility.FlutterPaxPrinterUtilityPlugin.onMethodCall(FlutterPaxPrinterUtilityPlugin.java:45)
E/AndroidRuntime(31235): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:258)
E/AndroidRuntime(31235): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/AndroidRuntime(31235): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:322)
E/AndroidRuntime(31235): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(D8$$SyntheticClass)
E/AndroidRuntime(31235): 	at android.os.Handler.handleCallback(Handler.java:751)
E/AndroidRuntime(31235): 	at android.os.Handler.dispatchMessage(Handler.java:95)
E/AndroidRuntime(31235): 	at android.os.Looper.loop(Looper.java:154)
E/AndroidRuntime(31235): 	at android.app.ActivityThread.main(ActivityThread.java:6127)
E/AndroidRuntime(31235): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(31235): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
E/AndroidRuntime(31235): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
Lost connection to device.
```
I even created a folder named  ```armeabi-v7a```  inside ```android/app/src/main/jniLibs``` and placed the file libDeviceConfig.so there but still getting the error

**Comment by X-SLAYER** [comment]
I added
```xml
<application
  ...
android:extractNativeLibs="true">
```

I got this new error

```
/AndroidRuntime(20652): FATAL EXCEPTION: main
E/AndroidRuntime(20652): Process: app.cash.grip, PID: 20652
E/AndroidRuntime(20652): java.lang.UnsatisfiedLinkError: dlopen failed: "/data/app/app.cash.grip-1/lib/arm64/libDeviceConfig.so" is 32-bit instead of 64-bit
E/AndroidRuntime(20652): 	at java.lang.Runtime.loadLibrary0(Runtime.java:989)
E/AndroidRuntime(20652): 	at java.lang.System.loadLibrary(System.java:1562)
E/AndroidRuntime(20652): 	at com.pax.dal.impl.utils.DeviceConfig.<clinit>(SourceFile:22)
E/AndroidRuntime(20652): 	at com.pax.dal.impl.utils.ServiceUtils.getDeviceEnable(SourceFile:90)
E/AndroidRuntime(20652): 	at com.pax.dal.impl.utils.ServiceUtils.isModuleEnable(SourceFile:102)
E/AndroidRuntime(20652): 	at com.pax.dal.impl.D.u(SourceFile:121)
E/AndroidRuntime(20652): 	at com.pax.dal.impl.D.init(SourceFile:128)
E/AndroidRuntime(20652): 	at com.pax.dal.impl.PrinterImplDecorator.init(SourceFile:55)
E/AndroidRuntime(20652): 	at com.mahatech.flutter_pax_printer_utility.PrinterUtility.init(PrinterUtility.java:43)
E/AndroidRuntime(20652): 	at com.mahatech.flutter_pax_printer_utility.FlutterPaxPrinterUtilityPlugin.onMethodCall(FlutterPaxPrinterUtilityPlugin.java:45)
E/AndroidRuntime(20652): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:258)
E/AndroidRuntime(20652): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/AndroidRuntime(20652): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:322)
E/AndroidRuntime(20652): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(D8$$SyntheticClass)
E/AndroidRuntime(20652): 	at android.os.Handler.handleCallback(Handler.java:751)
E/AndroidRuntime(20652): 	at android.os.Handler.dispatchMessage(Handler.java:95)
E/AndroidRuntime(20652): 	at android.os.Looper.loop(Looper.java:154)
E/AndroidRuntime(20652): 	at android.app.ActivityThread.main(ActivityThread.java:6127)
E/AndroidRuntime(20652): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(20652): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
E/AndroidRuntime(20652): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
Application finished.
```

**Comment by hectordz87** [comment]
I have the same error, could you find the solution?

**Comment by X-SLAYER** [comment]
> I have the same error, could you find the solution?

Yes I did the problem is from Flutter itself check [here ](https://github.com/flutter/flutter/issues/57237)

the solution is to build the app with this ndk filters then install it it will work 
if you plan to debug with this filter it will not work just build it and install it manually

````gradle
        ndk {
            abiFilters "armeabi-v7a"
        }

**Comment by reynirf** [comment]
The author sets ndkVersion in his example app build.gradle to prevent this error. 
I think it should be added to the README as the plugin won't work without it.

**Comment by yawerky** [comment]
Added Ndk version but still getting same error
