### ISSUE TITLE
Error when running .init on an A920

### ISSUE THREAD

**Issue by reynirf** [AuliaVailo/flutter_pax_printer_utility#15]
Hello. 
I followed the installation instructions and my app crashes when I try to init the plugin using `await FlutterPaxPrinterUtility.init`.

Using Flutter 3.16.0 (the latest on channel **stable**)

**Error:**
java.lang.UnsatisfiedLinkError: dalvik.system.DexClassLoader[DexPathList[[dex file "/data/user/0/is.codenorth.servicepoint.dev/files/nepcore.dex"],nativeLibraryDirectories=[/data/app/is.codenorth.servicepoint.dev-2/lib/arm, /data/resource/lib, /vendor/lib, /system/lib]]] couldn't find "libDeviceConfig.so"

**Stacktrace:**
E/AndroidRuntime(11598): 	at java.lang.Runtime.loadLibrary0(Runtime.java:984)
E/AndroidRuntime(11598): 	at java.lang.System.loadLibrary(System.java:1562)
E/AndroidRuntime(11598): 	at com.pax.dal.impl.utils.DeviceConfig.<clinit>(SourceFile:22)
E/AndroidRuntime(11598): 	at com.pax.dal.impl.utils.ServiceUtils.getDeviceEnable(SourceFile:90)
E/AndroidRuntime(11598): 	at com.pax.dal.impl.utils.ServiceUtils.isModuleEnable(SourceFile:102)
E/AndroidRuntime(11598): 	at com.pax.dal.impl.D.u(SourceFile:121)
E/AndroidRuntime(11598): 	at com.pax.dal.impl.D.init(SourceFile:128)
E/AndroidRuntime(11598): 	at com.pax.dal.impl.PrinterImplDecorator.init(SourceFile:55)
E/AndroidRuntime(11598): 	at com.mahatech.flutter_pax_printer_utility.PrinterUtility.init(PrinterUtility.java:43)
E/AndroidRuntime(11598): 	at com.mahatech.flutter_pax_printer_utility.FlutterPaxPrinterUtilityPlugin.onMethodCall(FlutterPaxPrinterUtilityPlugin.java:45)

**Comment by reynirf** [comment]
I now see that this is a duplicate of another issue (https://github.com/MAHAulia/flutter_pax_printer_utility/issues/11)

Closing this one.
