### ISSUE TITLE
Add support for PAX A80 (64 bit device)

### ISSUE THREAD

**Issue by tonyrbf96** [AuliaVailo/flutter_pax_printer_utility#21]
I am getting this error executing 
```dart
await FlutterPaxPrinterUtility.init;
```

## ERROR

FATAL EXCEPTION: main
Process: com.pinserve.prepaidmini, PID: 26229
java.lang.UnsatisfiedLinkError: dlopen failed: "/data/app/com.mahatech.flutter_pax_printer_utility_example-1/lib/arm64/libDeviceConfig.so" is 32-bit instead of 64-bit
 at java.lang.Runtime.loadLibrary0(Runtime.java:989)
 at java.lang.System.loadLibrary(System.java:1530)
 at com.pax.dal.impl.utils.DeviceConfig.<clinit>(SourceFile:22)
 at com.pax.dal.impl.utils.ServiceUtils.getDeviceEnable(SourceFile:90)
 at com.pax.dal.impl.utils.ServiceUtils.isModuleEnable(SourceFile:102)
 at com.pax.dal.impl.D.u(SourceFile:121)
 at com.pax.dal.impl.D.init(SourceFile:128)
 at com.pax.dal.impl.PrinterImplDecorator.init(SourceFile:55)
 at com.mahatech.flutter_pax_printer_utility.PrinterUtility.init(PrinterUtility.java:43)
 at com.mahatech.flutter_pax_printer_utility.FlutterPaxPrinterUtilityPlugin.onMethodCall(FlutterPaxPrinterUtilityPlugin.java:45)
 at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:267)
 at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:292)
 at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger
 at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(D8$$SyntheticClass)
 at android.os.Handler.handleCallback(Handler.java:751)
 at android.os.Handler.dispatchMessage(Handler.java:95)
 at android.os.Looper.loop(Looper.java:154)
 at android.app.ActivityThread.main(ActivityThread.java:6119)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:969)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:859)
 
## DEVICE
 Model A80
 Debug Only
 Android 7.1.1
 Kernel 3.10.65

**Comment by FifoTheHein** [comment]
I've managed to get my hands on the latest version of the NeptuneLight SDK from PAX. Give my fork a go and see if you have better luck. We've managed to get it printing on an Android 12 (64 bit) based PAX successfully. Turns out the files in the flutter_pax_printer_utility\android\src\main\jniLibs\arm64-v8a folder were just a copy of the 32 bit files and not the 64 bit files. I also updated the NettuneLight version to NeptuneLiteApi_V4.09.00_20240909. I created a pull request on the main branch; hopefully, the author will accept it soon. My fork with the changes: https://github.com/FifoTheHein/flutter_pax_printer_utility

I received the latest version of NeptuneLiteApi today and will be updating to it and testing. If all goes well, I'll push that update to my fork as well
